services:
  nodejs-app:
    image: nodejs-app:1.0.0
    container_name: nodejs_app_c
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT_OUT}:${PORT}
    environment:
      - PORT=${PORT}