services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx_nodejs_c
    ports:
      - 8080:80

  nodejs-app:
    command: npm run dev
    volumes:
      - ./src:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    